tester part for ivy nearly ok + still need to modify ivy interface and other small stuffs

diff --git a/panther/plugins/environments/network_environment/docker_compose/docker-compose.generated.yml b/panther/plugins/environments/network_environment/docker_compose/docker-compose.generated.yml
--- a/panther/plugins/environments/network_environment/docker_compose/docker-compose.generated.yml
+++ b/panther/plugins/environments/network_environment/docker_compose/docker-compose.generated.yml
@@ -1,4 +1,3 @@
-# TODO remove space
 name: QUIC_Client-Server_Communication_Test_II
 services:
   picoquic_server:
@@ -14,21 +13,28 @@ services:
       GID: "${GID}"
     tty: true
     stdin_open: true
+    # TODO fix in the docker
     cap_add:
       - CAP_NET_ADMIN
       - CAP_NET_RAW
     working_dir: "/opt/picoquic"
     # TODO protocol + duration
     command: 
-      - bash -c "
+      - /bin/sh -c '
+          set -x;
+          export PATH=$$PATH:$$ADDITIONAL_PATH;
+          export PYTHONPATH=$$PYTHONPATH:$$ADDITIONAL_PYTHONPATH;
+          env >> /app/logs/ivy_setup.log;
           while [ ! -f /app/sync_logs/ivy_ready ]; do
-                                echo 'Waiting for Ivy tester to be ready...' > /app/logs/tester_ready;
+                                echo "Waiting for Ivy tester to be ready..." >> /app/logs/tester_ready;
                                 sleep 2;
                             done;
-                            echo 'Ivy tester is ready, starting picoquic_server...' /app/logs/tester_ready; 
-          (tshark -a duration:10 -i any -w /app/logs/picoquic_server.pcap;) & (sleep 2; ./picoquicdemo -c /opt/certs/cert.pem -k /opt/certs/key.pem -a hq-interop -l - -n servername -D -L  -e eth0  -p 4443 > /app/logs/server.log 2>&1)"
+                            echo "Ivy tester is ready, starting picoquic_server..." >> /app/logs/tester_ready; 
+          (tshark -a duration:10 -i any -w /app/logs/picoquic_server.pcap;) & 
+          (./picoquicdemo -c /opt/certs/cert.pem -k /opt/certs/key.pem -a hq-interop -l - -n servername -D -L  -e eth0  -p 4443 > /app/logs/server.log 2>&1)'
+    # TODO fix sudo tshark
     volumes:
-      - /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-11-25_17-07-27/QUIC_Client-Server_Communication_Test_II/logs/picoquic_server:/app/logs/
+      - /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-11-28_16-49-21/QUIC_Client-Server_Communication_Test_II/logs/picoquic_server:/app/logs/
       - "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/cert.pem:/opt/certs/cert.pem"
       - "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/key.pem:/opt/certs/key.pem"
       - "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/ticket.key"
@@ -50,17 +56,112 @@ services:
       SSLKEYLOGFILE: "/app/logs/sslkeylogfile.txt" 
       UID: "${UID}"
       GID: "${GID}"
+      PROTOCOL_TESTED: ""
+      RUST_LOG: "debug"
+      RUST_BACKTRACE: "1"
+      SOURCE_DIR: "/opt/"
+      IVY_DIR: "/opt//panther_ivy"
+      PYTHON_IVY_DIR: "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/"
+      IVY_INCLUDE_PATH: "$$IVY_INCLUDE_PATH:/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/1.7"
+      Z3_LIBRARY_DIRS: "/opt//panther_ivy/submodules/z3/build"
+      Z3_LIBRARY_PATH: "/opt//panther_ivy/submodules/z3/build"
+      LD_LIBRARY_PATH: "$$LD_LIBRARY_PATH:/opt//panther_ivy/submodules/z3/build"
+      PROOTPATH: "/opt/"
+      ADDITIONAL_PYTHONPATH: "/app/implementations/quic-implementations/aioquic/src/:/opt//panther_ivy/submodules/z3/build/python:/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/"
+      ADDITIONAL_PATH: "/go/bin:/opt//panther_ivy/submodules/z3/build"
+      ZRTT_SSLKEYLOGFILE: "/opt//panther_ivy/protocol-testing/quic/last_tls_key.txt"
+      RETRY_TOKEN_FILE: "/opt//panther_ivy/protocol-testing/quic/last_retry_token.txt"
+      NEW_TOKEN_FILE: "/opt//panther_ivy/protocol-testing/quic/last_new_token.txt"
+      ENCRYPT_TICKET_FILE: "/opt//panther_ivy/protocol-testing/quic/last_encrypt_session_ticket.txt"
+      SESSION_TICKET_FILE: "/opt//panther_ivy/protocol-testing/quic/last_session_ticket_cb.txt"
+      SAVED_PACKET: "/opt//panther_ivy/protocol-testing/quic/saved_packet.txt"
+      initial_max_stream_id_bidi: "/opt//panther_ivy/protocol-testing/quic/initial_max_stream_id_bidi.txt"
+      active_connection_id_limit: "/opt//panther_ivy/protocol-testing/quic/active_connection_id_limit.txt"
+      initial_max_stream_data_bidi_local: "/opt//panther_ivy/protocol-testing/quic/initial_max_stream_data_bidi_local.txt"
+      initial_max_stream_data_bidi_remote: "/opt//panther_ivy/protocol-testing/quic/initial_max_stream_data_bidi_remote.txt"
+      initial_max_stream_data_uni: "/opt//panther_ivy/protocol-testing/quic/initial_max_stream_data_uni.txt"
+      initial_max_data: "/opt//panther_ivy/protocol-testing/quic/initial_max_data.txt"
+      INITIAL_VERSION: "1"
     tty: true
     stdin_open: true
+    # TODO fix in the docker
     cap_add:
       - CAP_NET_ADMIN
       - CAP_NET_RAW
     working_dir: "/opt/panther_ivy/protocol-testing/quic"
     # TODO protocol + duration
     command: 
-      - bash -c "cd /opt/panther_ivy/; PYTHONPATH=$PYTHONPATH:/opt/panther_ivy/ivy/ ivyc trace=false show_compiled=false target=test test_iters=100 /opt/panther_ivy/protocol-testing/quic/quic_tests/client_tests/quic_client_test_max.ivy && mv /opt/panther_ivy/protocol-testing/quic/quic_tests/client_tests/quic_client_test_max.* /opt/panther_ivy/protocol-testing/quic/build/ &&  touch /app/sync_logs/tester_ready && (tshark -a duration:10 -i any -w /app/logs/ivy_client.pcap;) & (sleep 2; cd /opt/panther_ivy/protocol-testing/quic && timeout 120 build//quic_client_test_max seed=0 the_cid=0         server_port=4443 iversion=1 server_addr=2130706433         client_port=4443 client_port_alt=4444 client_addr=2130706433  > /app/logs/tester.log 2>&1)"
+      - /bin/sh -c '
+          set -x;
+          export PATH=$$PATH:$$ADDITIONAL_PATH;
+          export PYTHONPATH=$$PYTHONPATH:$$ADDITIONAL_PYTHONPATH;
+          env >> /app/logs/ivy_setup.log;
+          
+        echo "Copying QUIC libraries..." >> /app/logs/ivy_setup.log &&
+        cp -f -a /opt/picotls/*.a "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/lib/" &&
+        cp -f -a /opt/picotls/*.a "/opt/panther_ivy/ivy/lib/" &&
+        cp -f /opt/picotls/include/picotls.h "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/picotls.h" &&
+        cp -f /opt/picotls/include/picotls.h "/opt/panther_ivy/ivy/include/picotls.h" &&
+        cp -r -f /opt/picotls/include/picotls/. "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/picotls" &&
+        cp -f "/opt/panther_ivy/protocol-testing/quic/quic_utils/quic_ser_deser.h" "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/1.7/" &&
+        
+        update_ivy_tool() {
+            echo "Updating Ivy tool..." >> /app/logs/ivy_setup.log;
+            cd "/opt/panther_ivy" || exit 1;
+            sudo python3.10 setup.py install >> /app/logs/ivy_setup.log 2>&1 &&
+            cp lib/libz3.so submodules/z3/build/python/z3 >> /app/logs/ivy_setup.log 2>&1 &&
+            echo "Copying updated Ivy files..." >> /app/logs/ivy_setup.log &&
+            find /opt/panther_ivy/ivy/include/1.7/ -type f -name "*.ivy" -exec cp {} /usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/1.7/ \; >> /app/logs/ivy_setup.log 2>&1 &&
+            echo "Copying updated Z3 files..." >> /app/logs/ivy_setup.log &&
+            cp -f -a /opt/panther_ivy/ivy/lib/*.a "/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/lib/" >> /app/logs/ivy_setup.log 2>&1;
+        }
+
+        update_ivy_tool &&
+        remove_debug_events() {
+            echo "Removing debug events..." >> /app/logs/ivy_setup.log;
+            printf "%s\n" "$@" | xargs -I {} sh -c "
+                if [ -f \"\$1\" ]; then
+                    sed -i \"s/^\\([^#]*debug_event.*\\)/##\\1/\" \"\$1\";
+                else
+                    echo \"File not found - \$1\" >> /app/logs/ivy_setup.log;
+                fi
+            " _ {};
+        }
+
+
+        restore_debug_events() {
+            echo "Restoring debug events..." >> /app/logs/ivy_setup.log;
+            printf "%s\n" "$@" | xargs -I {} sh -c "
+                if [ -f \"\$1\" ]; then
+                    sed -i \"s/^##\\(.*debug_event.*\\)/\\1/\" \"\\$1\";
+                else
+                    echo \"File not found - \$1\" >> /app/logs/ivy_setup.log;
+                fi
+            " _ {};
+        }
+
+        setup_ivy_model() {
+            echo "Setting up Ivy model..." >> /app/logs/ivy_setup.log &&
+            echo "Updating include path of Python with updated version of the project from /opt/panther_ivy/protocol-testing/quic" >> /app/logs/ivy_setup.log &&
+            echo "Finding .ivy files..." >> /app/logs/ivy_setup.log &&
+            find "/opt/panther_ivy/protocol-testing/quic" -type f -name "*.ivy" -exec sh -c "
+                echo \"Found Ivy file - \$1\" >> /app/logs/ivy_setup.log;
+                if [ 1 -gt 10 ]; then
+                    echo \"Removing debug events from \$1\" >> /app/logs/ivy_setup.log;
+                    remove_debug_events \"\$1\";
+                fi;
+                echo \"Copying Ivy file to include path...\" >> /app/logs/ivy_setup.log;
+                cp -f \"\$1\" \"/usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/1.7/\";
+            " _ {} \;;
+            ls -l /usr/local/lib/python3.10/dist-packages/ms_ivy-1.8.25-py3.10-linux-x86_64.egg/ivy/include/1.7/ >> /app/logs/ivy_setup.log;
+        }
+
+        setup_ivy_model && (cd /opt/panther_ivy/protocol-testing/quic/quic_tests/client_tests; PYTHONPATH=$$PYTHON_IVY_DIR ivyc trace=false show_compiled=false target=test test_iters=100 quic_client_test_max.ivy >> /app/logs/ivy_setup.log 2>&1 ;ls >> /app/logs/ivy_setup.log 2>&1 ; cp /opt/panther_ivy/protocol-testing/quic/quic_tests/client_tests/quic_client_test_max* /opt/panther_ivy/protocol-testing/quic/build/; ls /opt/panther_ivy/protocol-testing/quic/build/ >> /app/logs/ivy_setup.log 2>&1 ;  ) &&  ( touch /app/sync_logs/ivy_ready ) && ((touch /app/logs/ivy_client.pcap; tshark -a duration:10 -i any -w /app/logs/ivy_client.pcap;) & 
+          (sleep 5; cd /opt/panther_ivy/protocol-testing/quic && timeout 120 build//quic_client_test_max seed=0 the_cid=0         server_port=4443 iversion=1 server_addr=picoquic_server         client_port=4443 client_port_alt=4444 client_addr=picoquic_server  > /app/logs/tester.log 2>&1))'
+    # TODO fix sudo tshark
     volumes:
-      - /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-11-25_17-07-27/QUIC_Client-Server_Communication_Test_II/logs/ivy_client:/app/logs/
+      - /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-11-28_16-49-21/QUIC_Client-Server_Communication_Test_II/logs/ivy_client:/app/logs/
+      - "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/plugins/testers/panther_ivy/protocol-testing/quic:/opt/panther_ivy/protocol-testing/quic"
       - "shared_logs:/app/sync_logs"
       - "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/tester_ticket.key"
     networks:
